services:

  eureka-server:
    build:
      context: ./ms-eureka
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - ms-network

  api-gateway:
    build: ./ms-gateway
    container_name: api-gateway
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - ms-network

  ms-venta:
    build: ./ms-venta
    container_name: ms-venta
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - ms-network

  ms-boletas:
    build: ./ms-boleta
    container_name: ms-boletas
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - ms-network

  ms-usuarios:
    build: ./ms-usuario
    container_name: ms-usuarios
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - ms-network

  ms-producto:
    build: ./ms-producto
    container_name: ms-producto
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - ms-network

  ms-inventario:
    build: ./ms-inventario
    container_name: ms-inventario
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge