services:

  eureka-server:
    build:
      context: ./ms-eureka
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - ms-network

  api-gateway:
    build: ./ms-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - ms-network

  ms-venta:
    build: ./ms-venta
    container_name: ms-venta
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    environment:
      - SPRING_APPLICATION_NAME=ms-venta
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - DB_URL=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
      - DB_USER=postgres.rlsuzveutyfpasskdfix
      - DB_PASSWORD=Ns!nqpWK$C8bR$x
      
    networks:
      - ms-network

  ms-boletas:
    build: ./ms-boleta
    container_name: ms-boleta
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      - SPRING_APPLICATION_NAME=ms-boleta
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - DB_URL=spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
      - DB_USER=postgres.rlsuzveutyfpasskdfix
      - DB_PASSWORD=Ns!nqpWK$C8bR$x
    networks:
      - ms-network

  ms-usuarios:
    build: ./ms-usuario
    container_name: ms-usuario
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
    environment:
      - SPRING_APPLICATION_NAME=ms-usuario
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - DB_URL=spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
      - DB_USER=postgres.rlsuzveutyfpasskdfix
      - DB_PASSWORD=Ns!nqpWK$C8bR$x
    networks:
      - ms-network

  ms-producto:
    build: ./ms-producto
    container_name: ms-producto
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    environment:
      - SPRING_APPLICATION_NAME=ms-producto
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - DB_URL=spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
      - DB_USER=postgres.rlsuzveutyfpasskdfix
      - DB_PASSWORD=Ns!nqpWK$C8bR$x
    networks:
      - ms-network

  ms-inventario:
    build: ./ms-inventario
    container_name: ms-inventario
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
    environment:
      - SPRING_APPLICATION_NAME=ms-inventario
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - DB_URL=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
      - DB_USER=postgres.rlsuzveutyfpasskdfix
      - DB_PASSWORD=Ns!nqpWK$C8bR$x
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge