CREATE SCHEMA IF NOT EXISTS bd_pagos;

CREATE TABLE IF NOT EXISTS bd_pagos.pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monto_pago VARCHAR(100) NOT NULL,
    metodo_pago VARCHAR(20) NOT NULL,
    estado_pago VARCHAR(20) NOT NULL,
    codigo_Transaccion_pago VARCHAR(20) NOT NULL,
    fecha_pago VARCHAR(20) NOT NULL,
    moneda_pago DATE NOT NULL,
    descripcion_pago VARCHAR(20) NOT NULL
);

