CREATE SCHEMA IF NOT EXISTS bd_ventas;

CREATE TABLE IF NOT EXISTS bd_ventas.venta (
    id_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_venta TIMESTAMP NOT NULL,
    total_venta DOUBLE PRECISION NOT NULL,
    descripcion_venta VARCHAR(255) NOT NULL,
    monto_venta DOUBLE PRECISION NOT NULL,
    metodo_venta VARCHAR(50) NOT NULL,
    estado_venta VARCHAR(30) NOT NULL,
    codigo_transaccion_venta VARCHAR(100) NOT NULL UNIQUE
);