spring:
  application:
    name: ms-venta

  output:
    ansi:
      enabled: ALWAYS

  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.rlsuzveutyfpasskdfix
    password: Ns!nqpWK$C8bR$x
    driver-class-name: org.postgresql.Driver

    hikari:
      data-source-properties:
        prepareThreshold: 0

  sql:
    init:
      mode: never
      data-locations: ''

  jpa:
    defer-datasource-initialization: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: bd_ventas

    hibernate:
      ddl-auto: validate

    show-sql: true

  flyway:
    enabled: true
    default-schema: bd_ventas
    schemas: bd_ventas
    locations: classpath:db/migration

server:
  port: 8083

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true