server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ms-inventario-main
              uri: http://localhost:8085
              predicates:
                - Path=/api/v1/inventario/**
            - id: ms-productos
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/productos/**
            - id: boletas
              uri: lb://ms-boleta
              predicates:
                - Path=/api/v1/boletas/**
            - id: usuarios
              uri: lb://ms-usuario
              predicates:
                - Path=/api/v1/usuarios/**
            - id: ventas
              uri: lb://ms-venta
              predicates:
                - Path=/api/v1/ventas/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/