# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
spring:
  application:
    name: ms-producto
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.rlsuzveutyfpasskdfix
    password: Ns!nqpWK$C8bR$x
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: bd_productos
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: bd_productos
    validate-on-migrate: false
    out-of-order: true
server:
  port: 8084
logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate:
        SQL: INFO
    root: INFO
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true